// Styles
import styles from "./page.module.css";
// tailwindsCss Styles
import './globals.css'

export const metadata = {
  title: "Pricing card",
  description: "Generated by Mobin Karimi, you can copy blog component for sample card of your projects.",
};

export default function RootLayout({ children }: {children: any}) {
  return (
    <html lang="en">
      <body className={( styles.layout)}>{children}</body>
    </html>
  );
}
